// app/terms/page.tsx

import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-emerald-50/40 px-4 py-8 text-slate-900">
      <div className="mx-auto max-w-3xl rounded-2xl bg-white p-6 shadow-sm border border-emerald-100">
        <h1 className="text-2xl font-semibold mb-2">Terms of Use</h1>
        <p className="text-sm text-slate-500 mb-6">
          Last updated: {new Date().toLocaleDateString("en-IN")}
        </p>

        <section className="space-y-4 text-sm leading-relaxed">
          <p>
            These Terms of Use (&quot;Terms&quot;) govern your use of{" "}
            <strong>Koa</strong>, a minimal well-being companion chatbot
            (&quot;Koa,&quot; &quot;we,&quot; &quot;us,&quot; or
            &quot;our&quot;). By using this chatbot, you agree to these Terms.
            If you do not agree, please do not use Koa.
          </p>

          <h2 className="text-base font-semibold mt-4">1. Purpose of Koa</h2>
          <p>
            Koa is designed for <strong>general emotional well-being support</strong> only.
            It offers:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Short grounding or mindfulness micro-practices</li>
            <li>Gentle reflections and reframes</li>
            <li>Non-clinical check-ins around stress, mood, and motivation</li>
          </ul>
          <p className="mt-2">
            Koa is an <strong>AI-based educational and self-help tool</strong>, not a
            replacement for therapy, counselling, medical care, or crisis
            intervention.
          </p>

          <h2 className="text-base font-semibold mt-4">
            2. No Medical or Mental-Health Advice
          </h2>
          <p>
            Koa does <strong>not</strong>:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Diagnose any mental-health or medical condition</li>
            <li>Provide clinical treatment, therapy, or counselling</li>
            <li>Recommend or adjust medication</li>
            <li>Replace professional advice from a qualified expert</li>
          </ul>
          <p className="mt-2">
            Always consult a qualified professional (such as a doctor,
            psychologist, or counsellor) for concerns about your mental or
            physical health.
          </p>

          <h2 className="text-base font-semibold mt-4">3. Crisis &amp; Safety</h2>
          <p>
            Koa is <strong>not suitable for emergencies or crisis situations</strong>. If
            you are in immediate danger, feel unable to keep yourself safe, or
            are thinking about self-harm or harming others, please:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Contact local emergency services, or</li>
            <li>Reach out to a trusted person, or</li>
            <li>Call a local mental-health or crisis helpline if available</li>
          </ul>
          <p className="mt-2">
            Koa may gently encourage you to seek offline support, but it cannot
            assess risk in real time or intervene in emergencies.
          </p>

          <h2 className="text-base font-semibold mt-4">
            4. Use of AI-Generated Content
          </h2>
          <p>
            Responses in Koa are generated by an AI model based on your inputs
            and a curated set of well-being practices. As with all AI systems:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Responses may be incomplete, imperfect, or occasionally incorrect</li>
            <li>Different sessions may produce different answers</li>
            <li>
              You should use your own judgment before acting on any suggestions
            </li>
          </ul>
          <p className="mt-2">
            By using Koa, you acknowledge these limitations and agree that you
            are responsible for how you interpret and use the information
            provided.
          </p>

          <h2 className="text-base font-semibold mt-4">5. Acceptable Use</h2>
          <p>You agree not to use Koa to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Seek instructions for self-harm or harming others</li>
            <li>Request illegal, abusive, or violent content</li>
            <li>Harass, threaten, or bully others</li>
            <li>Try to bypass safety features or filters</li>
          </ul>

          <h2 className="text-base font-semibold mt-4">6. Data &amp; Privacy</h2>
          <p>
            This chatbot may log your interactions for the purposes of
            <strong> improving the system, debugging, or academic evaluation</strong>.
            Please avoid sharing sensitive personal information such as:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Full name, address, or contact details</li>
            <li>Financial information or passwords</li>
            <li>Highly sensitive personal or medical details</li>
          </ul>
          <p className="mt-2">
            This project is primarily for educational and demonstration purposes
            (e.g., an academic assignment). For more information about how your
            data is handled, please contact the project team or institution.
          </p>

          <h2 className="text-base font-semibold mt-4">
            7. No Warranty &amp; Limitation of Liability
          </h2>
          <p>
            Koa is provided on an <strong>&quot;as is&quot; and &quot;as available&quot;</strong> basis, without
            warranties of any kind. To the maximum extent permitted by law, the
            creators and institution are not liable for:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Any decisions you make based on Koa&apos;s responses</li>
            <li>Any harm, loss, or damages arising from use or inability to use Koa</li>
          </ul>

          <h2 className="text-base font-semibold mt-4">
            8. Changes to These Terms
          </h2>
          <p>
            These Terms may be updated from time to time to reflect changes in
            the project, technology, or legal requirements. The &quot;Last
            updated&quot; date at the top of this page indicates when the Terms
            were last revised.
          </p>

          <h2 className="text-base font-semibold mt-4">9. Contact</h2>
          <p>
            If you have questions about these Terms or about Koa, please reach
            out to the project team or course instructor.
          </p>

          <p className="mt-6 text-xs text-slate-500">
            By continuing to use Koa, you confirm that you have read and
            understood these Terms of Use.
          </p>
        </section>

        <div className="mt-8 text-xs text-slate-500">
          <Link href="/" className="underline">
            ← Back to Koa
          </Link>
        </div>
      </div>
    </main>
  );
}
